// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config'
import process from 'node:process'
import { defineConfig } from 'prisma/config'

export default defineConfig({
  schema: 'backend/prisma/schema.prisma',
  migrations: {
    path: 'backend/prisma/migrations',
    seed: 'node backend/prisma/seed.js',
  },
  datasource: {
    url: process.env.DATABASE_URL ?? '',
  },
})
